from dataclasses import dataclass
from pathlib import Path
from typing import List

@dataclass
class DatasetInfo:
    dataset_name: str
    num_classes: int  
    target_names: List[str]
    num_channels: int 
    samples: int
    sample_rate: int
    channels_names: List[str]
    subjects: int
    total_trials: int
    montage: str

ROOT_VOTING_SYSTEM_PATH: str = str(Path(__file__).parent.parent.parent.resolve())

aguilera_traditional_info = DatasetInfo(
    dataset_name="aguilera_traditional",
    num_classes=4,
    target_names=["Avanzar", "Retroceder", "Derecha", "Izquierda"],
    num_channels=24,
    samples=701,
    sample_rate=500,
    channels_names=[
        "FP1", 
        "FP2", 
        "F3", 
        "F4", 
        "C3", 
        "C4", 
        "P3", 
        "P4", 
        "O1", 
        "O2", 
        "F7", 
        "F8", 
        "T7", 
        "T8", 
        "P7", 
        "P8", 
        "Fz", 
        "Cz", 
        "Pz", 
        "M1", 
        "M2", 
        "AFz", 
        "CPz", 
        "POz"
    ],
    subjects=16,
    total_trials=120,
    montage="standard_1020"
)

aguilera_gamified_info = DatasetInfo(
    dataset_name="aguilera_gamified",
    num_classes=4,
    target_names=["Avanzar", "Derecha", "Izquierda", "Retroceder"],
    num_channels=24,
    samples=701,
    sample_rate=500,
    channels_names=[
        "FP1", 
        "FP2", 
        "F3", 
        "F4", 
        "C3", 
        "C4", 
        "P3", 
        "P4", 
        "O1", 
        "O2", 
        "F7", 
        "F8", 
        "T7", 
        "T8", 
        "P7", 
        "P8", 
        "Fz", 
        "Cz", 
        "Pz", 
        "M1", 
        "M2", 
        "AFz", 
        "CPz", 
        "POz"
    ],
    subjects=15,
    total_trials=120,
    montage="standard_1020"
)

# Dataset Nieto
nieto_info = DatasetInfo(
    dataset_name="nieto",
    num_classes=4,
    target_names=["Arriba", "Abajo", "Derecha", "Izquierda"],
    num_channels=128,
    samples=512,
    sample_rate=256,
    channels_names=[
        "A1", 
        "A2", 
        "A3", 
        "A4", 
        "A5", 
        "A6", 
        "A7", 
        "A8", 
        "A9", 
        "A10",
        "A11", 
        "A12", 
        "A13", 
        "A14", 
        "A15", 
        "A16", 
        "A17", 
        "A18", 
        "A19", 
        "A20", 
        "A21", 
        "A22", 
        "A23", 
        "A24", 
        "A25", 
        "A26", 
        "A27", 
        "A28", 
        "A29", 
        "A30", 
        "A31", 
        "A32", 
        "B1", 
        "B2", 
        "B3", 
        "B4", 
        "B5", 
        "B6", 
        "B7", 
        "B8", 
        "B9", 
        "B10", 
        "B11", 
        "B12", 
        "B13", 
        "B14", 
        "B15", 
        "B16", 
        "B17", 
        "B18", 
        "B19", 
        "B20", 
        "B21", 
        "B22", 
        "B23", 
        "B24", 
        "B25", 
        "B26", 
        "B27", 
        "B28", 
        "B29", 
        "B30", 
        "B31", 
        "B32", 
        "C1", 
        "C2", 
        "C3", 
        "C4", 
        "C5", 
        "C6", 
        "C7", 
        "C8", 
        "C9", 
        "C10", 
        "C11", 
        "C12", 
        "C13", 
        "C14", 
        "C15", 
        "C16", 
        "C17", 
        "C18", 
        "C19", 
        "C20", 
        "C21", 
        "C22", 
        "C23", 
        "C24", 
        "C25", 
        "C26", 
        "C27", 
        "C28", 
        "C29", 
        "C30", 
        "C31", 
        "C32", 
        "D1", 
        "D2", 
        "D3", 
        "D4", 
        "D5", 
        "D6", 
        "D7", 
        "D8", 
        "D9", 
        "D10", 
        "D11", 
        "D12", 
        "D13", 
        "D14", 
        "D15", 
        "D16", 
        "D17", 
        "D18", 
        "D19", 
        "D20", 
        "D21", 
        "D22", 
        "D23", 
        "D24", 
        "D25", 
        "D26", 
        "D27", 
        "D28", 
        "D29", 
        "D30", 
        "D31", 
        "D32"
    ],
    subjects=10,
    total_trials=200,
    montage="PENDING"
)

# Dataset Coretto
coretto_info = DatasetInfo(
    dataset_name="coretto",
    num_classes=6,
    target_names=["Arriba", "Abajo", "Derecha", "Izquierda"],
    num_channels=6,
    samples=342,
    sample_rate=256,
    channels_names=["F3", "F4", "C3", "C4", "P3", "P4"],
    subjects=15,
    total_trials=606,
    montage="standard_1020"
)

# Dataset Torres
torres_info = DatasetInfo(
    dataset_name="torres",
    num_classes=5,
    target_names=["Arriba", "Abajo", "Izquierda", "Derecha", "Seleccionar"],
    num_channels=14,
    samples=463,
    sample_rate=128,
    channels_names=[
        "AF3", 
        "F7", 
        "F3", 
        "FC5", 
        "T7", 
        "P7", 
        "O1", 
        "O2", 
        "P8", 
        "T8", 
        "FC6", 
        "F4", 
        "F8", 
        "AF4"
    ],
    subjects=27,
    total_trials=132,
    montage="standard_1020"
)

# Dataset IC BCI 2020
ic_bci_2020_info = DatasetInfo(
    dataset_name="ic_bci_2020",
    num_classes=5,
    target_names=["Hello", "Help me", "Stop", "Thank you", "Yes"],
    num_channels=64,
    samples=795,
    sample_rate=256,
    channels_names=[
        "FP1", 
        "FP2", 
        "F7", 
        "F3", 
        "Fz", 
        "F4", 
        "F8", 
        "FC5", 
        "FC1", 
        "FC2", 
        "FC6", 
        "T7", 
        "C3", 
        "Cz", 
        "C4", 
        "T8", 
        "TP9", 
        "CP5", 
        "CP1", 
        "CP2", 
        "CP6", 
        "TP10", 
        "P7", 
        "P3", 
        "Pz", 
        "P4", 
        "P8", 
        "PO9", 
        "O1", 
        "Oz", 
        "O2", 
        "PO10", 
        "AF7", 
        "AF3", 
        "AF4", 
        "AF8", 
        "F5", 
        "F1", 
        "F2", 
        "F6", 
        "FT9", 
        "FT7", 
        "FC3", 
        "FC4", 
        "FT8", 
        "FT10", 
        "C5", 
        "C1", 
        "C2", 
        "C6", 
        "TP7", 
        "CP3", 
        "CPz", 
        "CP4", 
        "TP8", 
        "P5", 
        "P1", 
        "P2", 
        "P6", 
        "PO7", 
        "PO3", 
        "POz", 
        "PO4", 
        "PO8"
    ],
    subjects=15,
    total_trials=350,
    montage="standard_1020"
)

# Dataset Nguyen 2019
nguyen_2019_info = DatasetInfo(
    dataset_name="nguyen_2019",
    num_classes=4,
    target_names=["left hand", "concentrate", "right hand", "split"],
    num_channels=60,
    samples=0,  # PENDIENTE
    sample_rate=0,  # PENDIENTE
    channels_names=[],  # PENDIENTE
    subjects=8,
    total_trials=0,  # PENDIENTE
    montage="PENDING"
)

# Dataset BrainCommand
braincommand_info = DatasetInfo(
    dataset_name="braincommand",
    num_classes=4,
    target_names=["Derecha", "Izquierda", "Arriba", "Abajo"],
    num_channels=8,
    samples=350,
    sample_rate=250,
    channels_names=["C4", "FC3", "F5", "C3", "F7", "Cz", "P3", "C5"],
    subjects=1,  # PENDIENTE
    total_trials=228,
    montage="standard_1020"
)

# Colección de todos los datasets
datasets_basic_infos = {
    "aguilera_traditional": aguilera_traditional_info,
    "aguilera_gamified": aguilera_gamified_info,
    "nieto": nieto_info,
    "coretto": coretto_info,
    "torres": torres_info,
    "ic_bci_2020": ic_bci_2020_info,
    "nguyen_2019": nguyen_2019_info,
    "braincommand": braincommand_info
}
